# located in /etc/dnsmasq.d/dhcp.conf
# 参考3.5小节

# Set the interface on which dnsmasq operates.
# If not set, all the interfaces is used.
interface=br_lan

# enable dnsmasq's DNS server functionality.
port=53

# If you want dnsmasq to listen for DHCP and DNS requests only on
# specified interfaces (and the loopback) give the name of the
# interface (eg eth0) here.
# Repeat the line for more than one interface.
#interface=
# Or you can specify which interface _not_ to listen on
#except-interface=
# Or which to listen on by address (remember to include 127.0.0.1 if
# you use this.)
# listen-address=127.0.0.1,192.168.2.1,172.17.0.1

# Change this line if you want dns to get its upstream servers from
# somewhere other that /etc/resolv.conf
resolv-file=/etc/resolv.conf

cache-size=15000

# Add domains which you want to force to an IP address here.
# The example below send any host in double-click.net to a local
# web-server.
address=/xuchengcat.cn/192.168.2.1

#no-resolv
#no-poll
#server=127.0.0.1#1053
#server=223.5.5.5

# To enable dnsmasq's DHCP server functionality.
# 设置可分配的IPv4段为192.168.2.1/24，其中192.168.2.101 ~ 192.168.2.254用于随机分配
# 192.168.2.100 预留给与服务器 IPv6 地址 fc00:192:168:2::100 对应的服务地址
dhcp-range=192.168.2.101,192.168.2.254,255.255.255.0,infinite
# Set gateway as Router.
dhcp-option=3,192.168.2.1
# Set DNS server as Router.
dhcp-option=6,192.168.2.1
# Set NTP server as Router
dhcp-option=42,192.168.2.1

# DHCPv6 config
# 服务器使用 ::100；有状态 DHCPv6 地址池为 ::2 到 ::ff
dhcp-range=fc00:192:168:2::2,fc00:192:168:2::ff,24h
# 发布 fc00:192:168:2::/64 的 SLAAC 前缀
dhcp-range=fc00:192:168:2::,slaac
dhcp-option=option6:dns-server,[fc00:192:168:2::100]
dhcp-option=option6:ntp-server,[fc00:192:168:2::100]
enable-ra
dhcp-authoritative

# Set static IPs of other PCs and the Router.
# 指定静态IP示例：
dhcp-host=D8:43:AE:9D:74:D5,XuchengGame,192.168.2.2,[fc00:192:168:2::2],infinite
dhcp-host=1A:5E:24:12:1c:9d,Exchange25G,192.168.2.10,[fc00:192:168:2::10],infinite
dhcp-host=40:EC:99:96:14:05,HanDeskTop  ,192.168.2.11,[fc00:192:168:2::11],infinite
# dhcp-host=24:CF:24:1A:D5:EB,RedMiWifi  ,192.168.2.20,[fc00:192:168:2::20],infinite
dhcp-host=58:95:D8:1A:83:1A,UnWifi     ,192.168.2.30,[fc00:192:168:2::30],infinite
dhcp-host=00:12:34:6B:C5:49,Cameraroom  ,192.168.2.90,[fc00:192:168:2::90],infinite
dhcp-host=E0:62:90:88:6B:59,Camera404  ,192.168.2.99,[fc00:192:168:2::99],infinite
# dhcp-host=00:11:22:33:44:55,ESXi,192.168.2.2,[fc00:192:168:2::2],infinite

# Logging.
log-facility=/var/log/dnsmasq/dnsmasq.log   # logfile path.
log-async=25
log-queries # log queries.
log-dhcp    # log dhcp related messages.
